### ISSUE TITLE
Issue with exporting div as image

### ISSUE THREAD

**Issue by zeyuyaoy** [saishackclub/vibez#1]
When exporting the image, the background gets cut off, and only the top left corner is shown. Text is not affected.

**Comment by spyeic** [comment]
Use img element instead of Image element:
https://github.com/saishackclub/vibez/blob/5b66f62af221939e3fb0ecf216737be326ef8df8/pages/generate.tsx#L107-L120

**Comment by spyeic** [comment]
Or you can add an unoptimized prop to the Image element.
